### ISSUE TITLE
Class 'WAQI' not found

### ISSUE THREAD

**Issue by pekingdutch** [azuyalabs/waqi#1]
Hi,

When trying out your module, I get: Fatal error: Uncaught Error: Class 'WAQI' not found in /var/www/html/waqi/beijing.php:10 Stack trace: #0 {main} thrown in /var/www/html/waqi/beijing.php on line 10

`<?php

error_reporting(E_ALL);
ini_set('display_errors',1);

echo "test";

require 'vendor/autoload.php';

$waqi = new WAQI('00000000000000000000000000000000000000000');

$waqi->getObservationByStation('beijing');
$waqi->getAQI();

?>`

Using PHP Version 7.1.12-1

Any ideas on what could cause this issue?

Thx

**Comment by stelgenhof** [comment]
Yes, the WAQI class is held in it's own namespace. You instantiated a WAQI object in the user land space, which doesn't exist there :). Use `use Azuyalabs\WAQI\WAQI;` in your code.

**Comment by pekingdutch** [comment]
I see. I understand. This indeed solved the problem.

Not related to WAQI, but maybe you know: I always get the results for Barrie, Ontario - regardless of what city I choose? Thx!

**Comment by stelgenhof** [comment]
I also get the results for "Barrie, Ontario". My guess is that if their API can't find your city or monitoring station it defaults to this city (I don't know why). 

My experience with this API is that picking the right monitoring station is kind of finicky. You might need to check their main website what the best monitoring station is nearby you (and what the exact name is).

**Comment by pekingdutch** [comment]
It looks like you must use the station id (idx) in the API call and you cannot use the name of the station. For example: the idx for beijing is 1451, using this in the API call: `https://api.waqi.info/feed/@1451/?token=<token>` works. 

To find the idx i used `http://api.waqi.info/search/?token=<token>&keyword=<city>`

It seems to me you cannot use the station name directly. I tried many cities and none of them worked. Always default to Barrie. However, if a station does not exists you get unknown station. 

So I think you are correct that there is an issue with their API.... I tried contacting them, but no response yet.

**Comment by stelgenhof** [comment]
According to their API documentation (http://aqicn.org/json-api/doc/) the feed endpoint can use the station index or city name for the parameter. Based on this documentation, I've coded this class.

Looks like their documentation is not inline with the actual API behavior then.... :(

**Comment by pekingdutch** [comment]
Indeed. I had the same problem. Thought I did something wrong, so I ended up using yours. Anyway, I found a way to make it work.
