### ISSUE TITLE
Historical data?

### ISSUE THREAD

**Issue by amaury1093** [azuyalabs/waqi#5]
Is it possible to get historical AQI data?

https://aqicn.org/data-platform/register/

**Comment by stelgenhof** [comment]
As far as I can tell the WAQI service does not provide any historical data itself. The provided link describes some efforts to have historical data but seems not to be part of the WAQI project. 

WAQI only gives current information on which this API is built on.

**Comment by amaury1093** [comment]
Hmm, have a look at https://aqicn.org/forecast/beijing/, there's some 48h historical data. I'm pretty sure they do store historical data to some extent, but yeah, it doesn't seem easily accessible to the public.

On a related note, does this library provide AQI forecast?

**Comment by stelgenhof** [comment]
They showcase more than actually the API offers. You can have a look at their documentation here: http://aqicn.org/json-api/doc/

This library is a wrapper around their API and they don't offer any AQI forecast data nor historical data via their API (based on their documentation).

**Comment by rahit** [comment]
Posting an update here. Looks like you can download historical data from this portal now: https://aqicn.org/historical/

**Comment by stelgenhof** [comment]
Thanks @rahit! Looking again at their API documentation, it doesn't seem to have any endpoints to get forecast or historical data (then again that documentation site was last updated in 2022 according to the footer).
